/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tagai;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author user
 */
public class Map extends javax.swing.JFrame {

    private GameEngine engine;
    private AIPlayer player1;
    private AIPlayer player2;
    
    /**
     * Creates new form Map
     */
    public Map() {
        initComponents();
    }

    public void start()
    {
        player1 = engine.getPlayer1();
        
        if(player1.IsIt())
        {
         lblIt.setForeground(Color.RED);
         lblIt.setText("Red (Player 1) Is It!");   
        }
        else{
         lblIt.setForeground(Color.BLUE);
         lblIt.setText("Blue (Player 2) Is It!");
        }
        Thread engineThread = new Thread(engine);
        engineThread.start();
    }
    
    /**
     * Handles all value updates and GUI changes upon end of game
     * @param p1 - player that is "it"
     * @param p2 - other player
     */
    public void handleGameOver(AIPlayer p1, AIPlayer p2)
    {
        
        //Stop game
        engine.timer.stop();
        
        //Update player values
        p1.setWins(p1.getWins() + 1);
        p1.setIsIt(false);
        p2.setIsIt(true);
        
        //Update It label
        p1.getSprite().removeAll();
        p2.setSprite(engine.drawItLabel(p2));
        
        
        //Refresh Game Panel and update score labels
        GamePanel.removeAll();
        
        
        if(p1.getSprite().getBackground() == Color.RED)
        {
            lblRedWins.setText(String.valueOf(p1.getWins()));
            lblWinner.setText("RED WINS!");
            lblIt.setForeground(Color.BLUE);
            lblIt.setText("Blue (Player 2) Is It!");
        }
        else {
            lblBlueWins.setText(String.valueOf(p1.getWins()));
            lblWinner.setText("BLUE WINS!");
            lblIt.setForeground(Color.RED);
            lblIt.setText("Red (Player 1) Is It!");  
        }
        
        
        p1.x = (int) Math.random() * GamePanel.getWidth()/2;
        p1.y = (int) Math.random() * GamePanel.getHeight()/2;
        p2.x = (int) Math.random() * GamePanel.getWidth()/2;
        p2.y = (int) Math.random() * GamePanel.getHeight()/2;
        
        //Start timer for winner label display
        timer.start();
        
        //Start new game
        engine.drawPlayers();
        
    }

    public void setEngine(GameEngine engine) {
        this.engine = engine;
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblRedWins = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblBlueWins = new javax.swing.JLabel();
        GamePanel = new javax.swing.JPanel();
        lblWinner = new javax.swing.JLabel();
        lblIt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitle.setText("AI vs. AI Tag!");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Red AI : ");

        lblRedWins.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblRedWins.setText("0");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Blue AI :");

        lblBlueWins.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblBlueWins.setText("0");

        GamePanel.setBackground(new java.awt.Color(0, 0, 0));
        GamePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout GamePanelLayout = new javax.swing.GroupLayout(GamePanel);
        GamePanel.setLayout(GamePanelLayout);
        GamePanelLayout.setHorizontalGroup(
            GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        GamePanelLayout.setVerticalGroup(
            GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        lblIt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblIt.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRedWins)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBlueWins)
                .addGap(120, 120, 120))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(lblWinner, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(281, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIt)
                .addGap(334, 334, 334))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblRedWins)
                    .addComponent(jLabel2)
                    .addComponent(lblBlueWins))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(lblWinner, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Map().setVisible(true);
            }
        });
    }
    
    ActionListener listener = new ActionListener() { 
        @Override
        public void actionPerformed(ActionEvent ae) {
            lblWinner.setText("");
            timer.stop();
        }
        
    };
    
    Timer timer = new Timer(2000, listener);

    public JPanel getGamePanel() {
        return GamePanel;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GamePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBlueWins;
    private javax.swing.JLabel lblIt;
    private javax.swing.JLabel lblRedWins;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWinner;
    // End of variables declaration//GEN-END:variables
}
